export const bdData = {
  Chittagong: {
    Comilla: [
      "Debidwar",
      "Barura",
      "Brahmanpara",
      "Chandina",
      "Chauddagram",
      "Daudkandi",
      "Homna",
      "Laksam",
      "Muradnagar",
      "Nangalkot",
      "Comilla Sadar",
      "Meghna",
      "Monohorgonj",
      "Sadar Dakshin",
      "Titas",
      "Burichong",
      "Lalmoi",
    ],
    Feni: [
      "Chhagolnaiya",
      "Feni Sadar",
      "Sonagazi",
      "Fulgazi",
      "Parshuram",
      "Dagonbhuiya",
    ],
    Brahmanbaria: [
      "Brahmanbaria Sadar",
      "Kasba",
      "Nasirnagar",
      "Sarail",
      "Ashuganj",
      "Akhaura",
      "Nabinagar",
      "Banchharampur",
      "Bijoynagar",
    ],
    Rangamati: [
      "Rangamati Sadar",
      "Kaptai",
      "Kaukhali",
      "Baghaichhari",
      "Barkal",
      "Longadu",
      "Rajasthali",
      "BilaiChhari",
      "Jurachhari",
      "Naniarchhar",
    ],
    Noakhali: [
      "Noakhali",
      "Companyganj",
      "Begumganj",
      "Hatia",
      "Subarnachar",
      "Kabirhat",
      "Senbagh",
      "Chatkhil",
      "Sonaimuri",
    ],
    Chandpur: [
      "Haimchar",
      "Kachuya",
      "Shahrasti",
      "Chandpur Sadar",
      "Matlab",
      "Hajiganj",
      "Matlab",
      "Faridganj",
    ],
    Lakshmipur: [
      "Lakshmipur Sadar",
      "Kamalnagar",
      "Raipur",
      "Ramgati",
      "Ramganj",
    ],
    Chattogram: [
      "Rangunia",
      "Sitakunda",
      "Mirsarai",
      "Patiya",
      "Sandwip",
      "Banshkhali",
      "Boalkhali",
      "Anwara",
      "Chandanaish",
      "Satkania",
      "Lohagara",
      "Hathazari",
      "Fatikchhari",
      "Raozan",
      "Karnaphuli",
    ],
    "Cox's Bazar": [
      "Cox's Bazar Sadar",
      "Chokoria",
      "Kutubdia",
      "Ukhiya",
      "Maheshkhali",
      "Pekua",
      "Ramu",
      "Teknaf",
    ],
    Khagrachari: [
      "Khagrachhari Sadar",
      "Dighinala",
      "Panchhari",
      "Lakshmichhari",
      "Mahalchhari",
      "Manikchhari",
      "Ramgar",
      "Matranga",
      "Guimara",
    ],
    Bandarban: [
      "Bandarban Sadar",
      "Alikadam",
      "Naikhyangchhari",
      "Roangchhari",
      "Lama",
      "Ruma",
      "Thanchi",
    ],
  },
  Rajshahi: {
    Sirajganj: [
      "Belkuchi",
      "Chouhali",
      "Kamarakhand",
      "Kazipur",
      "Rayganj",
      "Shahzadpur",
      "Sirajganj",
      "Tarsash",
      "Ullapara",
    ],
    Pabna: [
      "Sujanagar",
      "Ishwardi",
      "Vhangura",
      "Pabna Sadar",
      "Bera",
      "Atghoria",
      "Chatmohar",
      "Santhia",
      "Faridpur",
    ],
    Bogura: [
      "Kahalu",
      "Bogura Sadar",
      "Sariakandi",
      "Shahjahanpur",
      "Dupchachia",
      "Adamdighi",
      "Nandigram",
      "Sonatola",
      "Dhunat",
      "Gabtali",
      "Sherpur",
      "Shibganj",
    ],
    Rajshahi: [
      "Paba",
      "Durgapur",
      "Mohanpur",
      "Charghat",
      "Puthia",
      "Bagha",
      "Godagari",
      "Tanore",
      "Bagmara",
    ],
    Natore: [
      "Natore Sadar",
      "Singra",
      "Baraiagram",
      "Bagatipara",
      "Lalpur",
      "Gurudaspur",
      "Noldanga",
    ],
    Jaipurhat: [
      "Akkelpur",
      "Kalai",
      "Khetlal",
      "Panchbibi",
      "Jaipurhat Sadar",
    ],
    Chapainawabganj: [
      "Chapainawabganj Sadar",
      "Gomostapur",
      "Nachol",
      "Bholahat",
      "Shibganj",
    ],
    Naogaon: [
      "Mahadebpur",
      "Badalgachi",
      "Pattnitala",
      "Dhamoirhat",
      "Niamatpur",
      "Manda",
      "Atrai",
      "Raninhgar",
      "Naogaon Sadar",
      "Porasha",
      "Saphahar",
    ],
  },
  Khulna: {
    Jessore: [
      "Monirampur",
      "Abhoynagar",
      "Bagherpara",
      "Chougachha",
      "Jhikorgacha",
      "Keshabpur",
      "Jessore Sadar",
      "Sharsa",
    ],
    Satkhira: [
      "Ashashuni",
      "Debhata",
      "Kalaroa",
      "Satkhira Sadar",
      "Shyamnagar",
      "Tala",
      "Kaliganj",
    ],
    Meherpur: ["Mujibnagar", "Meherpur Sadar", "Gangni"],
    Narail: ["Narail Sadar", "Lohagara", "Kalia"],
    Chuadanga: ["Chuadanga Sadar", "Alamdanga", "Damurhuda", "Jibonnagar"],
    Kushtia: [
      "Kushtia Sadar",
      "Kumarkhali",
      "Khoksa",
      "Mirpur",
      "Doulotpur",
      "Vheramara",
    ],
    Magura: ["Shalikha", "Shreepur", "Magura Sadar", "Mohammadpur"],
    Khulna: [
      "Paikgacha",
      "Phultala",
      "Dighalia",
      "Rupsa",
      "Terkhada",
      "Dumuria",
      "Batiaghata",
      "Dakop",
      "Koyra",
    ],
    Bagerhat: [
      "Fakirhat",
      "Bagerhat Sadar",
      "Mollahat",
      "Sharankhola",
      "Rampal",
      "Mordelgang",
      "Kachuya",
      "Mongla",
      "Chitalmari",
    ],
    Jhenaidah: [
      "Jhenaidah Sadar",
      "Shailkupa",
      "Horinakundu",
      "Kaliganj",
      "Kotchadpur",
      "Mahespur",
    ],
  },
  Barisal: {
    Jhalokathi: ["Jhalokathi Sadar", "Kathalia", "Nolchiti", "Rajapur"],
    Patuakhali: [
      "Baufal",
      "Patuakhali Sadar",
      "Dumki",
      "Dashmina",
      "Kalapara",
      "Mirzagang",
      "Golachipa",
      "Rangabali",
    ],
    Pirojpur: [
      "Pirojpur Sadar",
      "Nazirpur",
      "Kaukhali",
      "Bhandaoria",
      "Mothbari",
      "Nesarabad",
      "Indurkani",
    ],
    Barisal: [
      "Barisal Sadar",
      "Bakerganj",
      "Babugonj",
      "Ujirpur",
      "Banaripara",
      "Gournadi",
      "Agaillajhura",
      "Mehendiganj",
      "Muladi",
      "Hijla",
    ],
    Bhola: [
      "Bhola Sadar",
      "Borhan Uddin",
      "Charfasson",
      "Doulatkhan",
      "Monpura",
      "Tajumuddin",
      "Lalmohan",
    ],
    Barguna: [
      "Amtali",
      "Barguna Sadar",
      "Betagi",
      "Bamna",
      "Patharghata",
      "Taltali",
    ],
  },
  Sylhet: {
    Sylhet: [
      "Balaganj",
      "Bianibazar",
      "Bishwanath",
      "Companyganj",
      "Fenchuganj",
      "Golapganj",
      "Goyainghat",
      "Jaintapur",
      "Kanighat",
      "Sylhet Sadar",
      "Jakiganj",
      "Dakhin Surma",
      "Osmani",
    ],
    Moulvibazar: [
      "Bodolkha",
      "Kamalganj",
      "Kulaura",
      "Moulvibazar Sadar",
      "Rajnagar",
      "Srimongal",
      "Juri",
    ],
    Habiganj: [
      "Nabiganj",
      "Bahubal",
      "Azmiriganj",
      "Baniyachang",
      "Lakhai",
      "Chunarughat",
      "Habiganj Sadar",
      "Madhabpur",
      "Shayestaganj",
    ],
    Sunamganj: [
      "Sunamganj Sadar",
      "Dakhin Sunamganj",
      "Bishwambharpur",
      "Chatak",
      "Jagannathpur",
      "Dowarabazar",
      "Tahirpur",
      "Dharmapasha",
      "Jamalganj",
      "Shalla",
      "Deraai",
      "Madhyanagar",
    ],
  },
  Dhaka: {
    Narsingdi: [
      "Belabo",
      "Monohardi",
      "Narsingdi",
      "Palash",
      "Raipur",
      "Shibpur",
    ],
    Gazipur: ["Kaliganj", "Kaliakair", "Kapasia", "Gazipur Sadar", "Sripur"],
    Shariatpur: [
      "Shariatpur Sadar",
      "Naria",
      "Jajira",
      "Gosairhat",
      "Vhedorgonj",
      "Damudya",
    ],
    Narayanaganj: [
      "Arai Hazar",
      "Bandar",
      "Narayanaganj Sadar",
      "Rupganj",
      "Sonargaon",
    ],
    Tangail: [
      "Bashail",
      "Bhuayapur",
      "Delduar",
      "Ghatial",
      "Gopalpur",
      "Madhupur",
      "Mirzapur",
      "Nagarpor",
      "Sakhipur",
      "Tangail Sadar",
      "Kalihati",
      "Sadar",
    ],
    Munshiganj: ["Sadar", "Madaripur", "Lohajang", "Shibchar", "Munsiganj"],
  },
  Rangpur: {
    Panchgadh: ["Panchgadh", "Debiganj", "Boda", "Atoyar", "Tetulia"],
    Dinajpur: [
      "Nababganj",
      "Birganj",
      "Ghoraghat",
      "Birampur",
      "Parbatipur",
      "Bochaganj",
      "Kaharol",
      "Phulbari",
      "Dinajpur Sadar",
      "Hakimpur",
      "Khansama",
      "Biral",
      "Chirirbandar",
    ],
    Lalmonirhat: [
      "Lalmonirhat Sadar",
      "Kaliganj",
      "Hatibandha",
      "Patgram",
      "Aditmari",
    ],
    Nilphamari: [
      "Saidpur",
      "Domar",
      "Dimla",
      "Jaladhaka",
      "Kishorganj",
      "Nilphamari Sadar",
    ],
    Gaibandha: [
      "Sadullapur",
      "Gaibandha Sadar",
      "Polashbari",
      "Saghata",
      "Govindganj",
      "Sundarganj",
      "Phulchhari",
    ],
    Thakurgaon: [
      "Thakurgaon Sadar",
      "Pirganj",
      "Ranisonkail",
      "Horipur",
      "Baliadangi",
    ],
    Rangpur: [
      "Rangpur Sadar",
      "Gongachra",
      "Taraganj",
      "Badarganj",
      "Mithapukur",
      "Pirganj",
      "Kounia",
      "Pirghacha",
    ],
    Kurigram: [
      "Kurigram Sadar",
      "Nageshwari",
      "Bhurungamari",
      "Phulbari",
      "Rajarhat",
      "Ulipur",
      "Chilmari",
      "Roumari",
      "Char Rajibpur",
    ],
  },
  Mymensingh: {
    Sherpur: [
      "Sherpur Sadar",
      "Nalitabari",
      "Shreebordhi",
      "Nakla",
      "Jhinaigati",
    ],
    Mymensingh: [
      "Phulbari",
      "Trishal",
      "Bhaluka",
      "Muktagacha",
      "Mymensingh Sadar",
      "Dhowaura",
      "Phulpur",
      "Haluaghat",
      "Gouripur",
      "Gaforgaon",
      "Ishwarganj",
      "Nandail",
      "Tarakanda",
    ],
    Jamalpur: [
      "Jamalpur Sadar",
      "Melandha",
      "Islampur",
      "Dewanganj",
      "Sarishabari",
      "Madaraganj",
      "Baksiganj",
    ],
    Netrakona: [
      "Barhatta",
      "Durga Pur",
      "Kenduya",
      "Atpara",
      "Modan",
      "Khaliajuri",
      "Kolmakanda",
      "Mohanganj",
      "Purbdhala",
      "Netrakona Sadar",
    ],
  },
};
